language: ruby

rvm:
    - "2.1"

before_script:
  - "psql -c 'create role sample_app_4_0 SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database sample_app_4_0_test;' -U postgres postgres"
  - "bundle exec rake db:migrate"
