language: ruby
rvm:
- 2.0.0
before_script: bundle exec rake db:setup RAILS_ENV=test
before_install: gem update bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
